projects:
  serverlessapireactap:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphQL/todo.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphQL
